export { default as userRoutes } from "./userRoutes.js"
export { default as authRoutes } from "./authRoutes.js"
export { default as adminRoutes } from "./adminRoutes.js"
export { default as storageRoute } from "./storageRoute.js"
export { default as aiRoute } from "./aiRoute.js"
