export { default as UserModel } from "./User.js"
export { default as OtpModel } from "./Otp.js"
export { default as ApartamentTypeModel } from "./ApartamentType.js"
export { default as HouseTypeModel } from "./HouseType.js"
export { default as GarageTypeModel } from "./GarageType.js"
export { default as PlotTypeModel } from "./PlotType.js"
export { default as UserFavouriteModel } from "./UserFavourite.js"
